process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';

const { readFileSync } = require('fs');
const { Fireblocks, TransferPeerPathType } = require("@fireblocks/ts-sdk");

const FIREBLOCKS_API_SECRET_PATH = "../../editor_sandbox_lbg_user_secret.key";

// Initialize a Fireblocks API instance with local variables
const fireblocks = new Fireblocks({
    apiKey: "68f17824-2bc4-4803-b573-8d36a562f72a",
    basePath: "https://sandbox-api.fireblocks.io/v1",
    secretKey: readFileSync(FIREBLOCKS_API_SECRET_PATH, "utf8"),
});

// creating a new vault account
async function createVault() {
    try {
        const vault = await fireblocks.vaults.createVaultAccount({
            createVaultAccountRequest: {
                name: 'Vault generated by SDK',
                hiddenOnUI: false,
                autoFuel: false
            }
        });
        console.log(JSON.stringify(vault.data, null, 2))
    } catch (e) {
        console.log(e);
    }
}


//retrive vault accounts
async function getVaultPagedAccounts(limit) {
    try {
        const vaults = await fireblocks.vaults.getPagedVaultAccounts({
            limit
        });
        console.log(JSON.stringify(vaults.data, null, 2))
    } catch (e) {
        console.log(e);
    }
}

// create a transaction
async function createTransaction(assetId, amount, srcId, destId) {
    try {
        let payload = {
            assetId,
            amount,
            source: {
                type: TransferPeerPathType.VaultAccount,
                id: String(srcId)
            },
            destination: {
                type: TransferPeerPathType.VaultAccount,
                id: String(destId)
            },
            note: "Transfer HBAR"
        };

        const result = await fireblocks.transactions.createTransaction({ transactionRequest: payload });
        console.log(JSON.stringify(result, null, 2));
    } catch (error) {
            console.error('Error creating transaction:', error);
        }
    
    }


/*
createVault()
getVaultPagedAccounts(5)

createTransaction("HBAR_TEST", "0.1", "1", "3").catch(error => {
    console.error('Error creating transaction:', error);
});
*/

module.exports = {createTransaction, getVaultPagedAccounts, createTransaction}
